server:
  port: 8088
  
spring.cloud.stream.kafka.binder.brokers: 172.17.0.8:9092

spring.cloud.stream:
  function:
    definition: orderEventProcessor;historyEventPublisher
  bindings:
    orderEventProcessor-in-0:
      destination: order-events
    orderEventProcessor-out-0:
      destination: payment-events
    historyEventPublisher-out-0:
      destination: history-events